
spring:
  profiles:
    active: dev
----
spring:
  port: 9999
  profiles: dev
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:7001/eureka/
    instance:
      prefer-ip-address: true #使用ip注册到注册中心
  spring:
    application:
      name: AIGOU_PLAT
---
spring:
  port: 6666
  profiles: test
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:7001/eureka/
    instance:
      prefer-ip-address: true #使用ip注册到注册中心
  spring:
    application:
      name: AIGOU_PLAT